version: '3.9'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  php:
    image: php:7.4-apache
    container_name: php74-apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /Users/GTI-PC/Documents/PROG/PHP/teste_tecnico/src/:/var/www/html